isim = input("isminiz nedir? ")
print ( "merhaba " + isim)
sever = input(" ne yemeyi seversiniz? ")
print("ben de " + sever + " yemeyi seviyorsunuz")
print("merhaba " + isim + " " + sever  + " yemeyi seviyor ")